doctrine:
  dbal:
    url: "%env(resolve:DATABASE_URL)%"
    types:
      page_id: SocialNetworksPublisher\Infrastructure\Persistence\Doctrine\Types\PageIdType
      page_name: SocialNetworksPublisher\Infrastructure\Persistence\Doctrine\Types\PageNameType
      social_network: SocialNetworksPublisher\Infrastructure\Persistence\Doctrine\Types\SocialNetworksType
      posts: SocialNetworksPublisher\Infrastructure\Persistence\Doctrine\Types\PostsType
      post_status: SocialNetworksPublisher\Infrastructure\Persistence\Doctrine\Types\PostStatusType


  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    controller_resolver:
      auto_mapping: true
    mappings:
      SocialNetworksPublisher:
        is_bundle: false
        type: xml
        dir: "%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Mapping"
        prefix: 'SocialNetworksPublisher\Domain\Model'
