doctrine:
  dbal:
    url: "%env(resolve:DATABASE_URL)%"
    types:
      # post_id: SocialNetworksPublisher\Infrastructure\Persistence\Doctrine\Types\PostIdType
      # author: SocialNetworksPublisher\Infrastructure\Persistence\Doctrine\Types\AuthorType
      # content: SocialNetworksPublisher\Infrastructure\Persistence\Doctrine\Types\ContentType
      # status: SocialNetworksPublisher\Infrastructure\Persistence\Doctrine\Types\StatusType
      # page: SocialNetworksPublisher\Infrastructure\Persistence\Doctrine\Types\PageType
      # hash_tag_array: SocialNetworksPublisher\Infrastructure\Persistence\Doctrine\Types\HashTagArrayType
      page_id: SocialNetworksPublisher\Infrastructure\Persistence\Doctrine\Types\PageIdType
      page_name: SocialNetworksPublisher\Infrastructure\Persistence\Doctrine\Types\PageNameType
      social_network: SocialNetworksPublisher\Infrastructure\Persistence\Doctrine\Types\SocialNetworksType
      post_ids: SocialNetworksPublisher\Infrastructure\Persistence\Doctrine\Types\PostIdsType

  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    controller_resolver:
      auto_mapping: true
    mappings:
      SocialNetworksPublisher:
        is_bundle: false
        type: xml
        dir: "%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Mapping"
        prefix: 'SocialNetworksPublisher\Domain\Model'
