#!/bin/sh

bin/php vendor/bin/phpcbf --standard=PSR12 ./src ./tests
bin/php vendor/bin/phpcs --standard=PSR12 ./src ./tests

bin/php vendor/bin/phpstan analyse --level=10 ./src
bin/php vendor/bin/phpstan analyse --level=10 ./tests --memory-limit 256M

bin/phpunit --testsuite all
