services:
  nginx:
    image: "${COMPOSE_PROJECT_NAME}-nginx"
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - php
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - "./:/var/${COMPOSE_PROJECT_NAME}"
    ports:
      - "172.17.0.1:10980:80"
    networks:
      - ${COMPOSE_PROJECT_NAME}-network

  php:
    image: "${COMPOSE_PROJECT_NAME}-php"
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    user: "${USERID}:${GROUPID}"
    volumes:
      - "./:/var/${COMPOSE_PROJECT_NAME}"
      - "./:$PWD"
    working_dir: $PWD
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - ${COMPOSE_PROJECT_NAME}-network

  mariadb:
    image: ${COMPOSE_PROJECT_NAME}-mariadb:latest
    build:
      context: .
      dockerfile: docker/mariadb/Dockerfile
      tags: 
        - latest
    restart: always
    volumes:
      - ${DATA_PATH}/${COMPOSE_PROJECT_NAME}/mariadb:/var/lib/mysql
      - ./mariabackup:/backup
    env_file:
      - ./docker/mariadb/db.env
    networks:
      - ${COMPOSE_PROJECT_NAME}-network
    
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: "${COMPOSE_PROJECT_NAME}-phpmyadmin"
    restart: always
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb
    ports:
      - "172.17.0.1:10990:80"
    networks:
      - ${COMPOSE_PROJECT_NAME}-network

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    restart: always
    environment:
      PORT: 8080
      SUPPORTED_SUBMIT_METHODS: "['get', 'post', 'put', 'delete', 'patch']"
      SWAGGER_JSON: /v1/doc.yaml
    volumes:
      - ./docker/swagger/v1:/v1
    ports:
      - "172.17.0.1:10902:8080"
    networks:
      - ${COMPOSE_PROJECT_NAME}-network

networks:
  socialnetworkspublisher-network:
    driver: bridge
    name: "${COMPOSE_PROJECT_NAME}-network"
    enable_ipv6: true
    ipam:
      config:
        - subnet: fdff:1:29::/112
          gateway: fdff:1:29::1
