openapi: 3.1.0
info:
  title: SocialNetworksPublisher API
  version: 1.0.0
servers:
  - url: /api/v1
    description: Local server
  - url: http://172.17.0.1:10980/api/v1
    description: Local server
paths:
  /post/publish:
    post:
      summary: Publish a post on social networks
      operationId: publishPost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                socialNetworks:
                  type: string
                  description: The social network to post to
                  example: simpleBlog
                authorId:
                  type: string
                  description: The ID of the author on the social network
                  example: 1584514
                pageId:
                  type: string
                  description: The ID of the page where the post will be published
                  example: 4a75fe6
                content:
                  type: string
                  description: The content of the post
                  example: Ceci est un simple post
                hashtag:
                  type: string
                  description: Optional hashtags for the post
                  example: "#test, #FizzBuzz"
      responses:
        '201':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates whether the publication was successful
                    example: true
                  errorCode:
                    type: string
                    description: Name of the exception class if any error occurs
                    example: null
                  data:
                    type: object
                    properties:
                      postId:
                        type: string
                        description: The ID of the published post
                        example: pos_664c52f9c90cb
                    description: Data returned by the publication service
                  message:
                    type: string
                    description: Message associated with the response
                    example: ""
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates whether the publication was successful
                    example: false
                  errorCode:
                    type: string
                    description: Name of the exception class if any error occurs
                    example: InvalidRequestException
                  data:
                    type: object
                    description: Data returned by the publication service
                  message:
                    type: string
                    description: Message associated with the response
                    example: Invalid request
        '422':
          description: Unprocessable entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates whether the publication was successful
                    example: false
                  errorCode:
                    type: string
                    description: Name of the exception class if any error occurs
                    example: UnprocessableEntityException
                  data:
                    type: object
                    description: Data returned by the publication service
                  message:
                    type: string
                    description: Message associated with the response
                    example: Unprocessable entity
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates whether the publication was successful
                    example: false
                  errorCode:
                    type: string
                    description: Name of the exception class if any error occurs
                    example: InternalServerErrorException
                  data:
                    type: object
                    description: Data returned by the publication service
                  message:
                    type: string
                    description: Message associated with the response
                    example: Internal server error
